const jCategory = [
    {
        index: 0,
        image: "images/google.png",
        title: "Web Developer",
        rate: "$900-1200/m",
        av: "Full-Time",
        companyName: "Google",
        location: "Hyderabad",
        vacancy: "1",
        hours: "50h/week",
        description: "The web developer is responsible for planning and developing software solutions and web applications, supporting and maintaining a company’s websites and digital products. The day-to-day work of the web developer highly depends on constantly evolving internet innovations.",
        workplace: "Work-from-home",
        education: "Bachelor's Degree in any Computer Science Course.",
        experience: "2 to 5 Years",
    },
    {
        index: 1,
        image: "images/uber.png",
        title: "Freelancer",
        rate: "$900-1200/m",
        av: "Freelancers",
        companyName: "Uber",
        location: "Remote",
        vacancy: "Multiple",
        hours: "Flexible",
        description: "As a freelancer with Uber, you will work on different tech and design projects depending on the company’s requirements. You will collaborate with teams to develop innovative solutions while working remotely.",
        workplace: "Remote",
        education: "No specific degree required, skills-based hiring.",
        experience: "0 to 2 Years",
    },
    {
        index: 2,
        image: "images/linkedin.png",
        title: "Business Associate",
        rate: "$900-1200/m",
        av: "Part-Time",
        companyName: "LinkedIn",
        location: "Bengaluru",
        vacancy: "2",
        hours: "20h/week",
        description: "The Business Associate role at LinkedIn involves analyzing market trends, supporting business strategies, and engaging with clients to improve sales and marketing outcomes.",
        workplace: "Hybrid",
        education: "Bachelor's in Business Administration or related field.",
        experience: "1 to 3 Years",
    },
    {
        index: 3,
        image: "images/facebook.png",
        title: "Digital Marketing Specialist",
        rate: "$900-1200/m",
        av: "Full-Time",
        companyName: "Meta (Facebook)",
        location: "Mumbai",
        vacancy: "3",
        hours: "45h/week",
        description: "As a Digital Marketing Specialist at Meta, you will be responsible for planning, implementing, and optimizing online advertising campaigns. You will work on SEO, PPC, and content marketing strategies.",
        workplace: "On-site",
        education: "Bachelor’s Degree in Marketing, Communications, or a related field.",
        experience: "2 to 4 Years",
    },
    {
        index: 4,
        image: "images/yahoo.png",
        title: "User Experience Designer",
        rate: "$900-1200/m",
        av: "Part-Time",
        companyName: "Yahoo",
        location: "Chennai",
        vacancy: "1",
        hours: "25h/week",
        description: "A UX Designer at Yahoo is responsible for designing and improving the user experience of digital products, including websites and mobile apps. You will work with product managers and developers to create seamless interfaces.",
        workplace: "Hybrid",
        education: "Bachelor’s in Design, HCI, or a related field.",
        experience: "1 to 3 Years",
    }
];
